name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          gcc
          git
    - uses: actions/checkout@v4

    - name: Set up Chocolatey
      run: choco install chocolatey
    - name: Install dependencies
      run: choco install ghc cabal msys2 

    - name: Install dependencies
    - shell: msys2 {0}
      run: |
        uname -a
        pwd
        ls -lah
