name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          gcc
          git
    - uses: actions/checkout@v4

    - name: Set up Chocolatey
      run: choco install chocolatey
      
    - name: Install dependencies
      run: choco install ghc cabal

    - name: Update cabal
      run: cabal update

    - name: Build jhcr
      run: msys2 -c 'PATCH_LVL=126 COMMONJ=common-1.26a.j make build'
      
    - uses: actions/upload-artifact@v4
      with:
        name: jhcr.exe
        path: dist-newstyle/**/jhcr.exe
